-- Valori di partenza per i testi configurabili del sito: replicano i testi
-- gia' presenti sul sito, cosi' nulla cambia visivamente finche' non vengono
-- modificati da admin.
INSERT INTO site_texts (text_key, value, category, label, sort_order) VALUES
('home.hero.ctaPrimary', 'Prenota una consulenza', 'home', 'Hero: testo pulsante principale', 1),
('home.hero.ctaSecondary', 'Scopri i servizi', 'home', 'Hero: testo pulsante secondario', 2),
('home.hero.scrollLabel', 'Scorri', 'home', 'Hero: etichetta "scorri" in basso', 3),
('home.services.eyebrow', 'Cosa offro', 'home', 'Sezione Servizi (home): eyebrow', 10),
('home.services.title', 'Tre modi per portare la mia cucina da te', 'home', 'Sezione Servizi (home): titolo', 11),
('home.services.description', 'Dalla cena tra amici al lancio della tua attività: ogni servizio è pensato su misura, partendo da quello che ti serve davvero.', 'home', 'Sezione Servizi (home): descrizione', 12),
('home.recipes.eyebrow', 'A Modo Mio', 'home', 'Sezione A Modo Mio (home): eyebrow', 20),
('home.recipes.title', 'Un assaggio di quello che cucino', 'home', 'Sezione A Modo Mio (home): titolo', 21),
('home.recipes.description', 'Ricette di famiglia e qualche idea più creativa: ogni menu nasce da "A Modo Mio", adattato ai tuoi gusti e all''occasione.', 'home', 'Sezione A Modo Mio (home): descrizione', 22),
('home.recipes.ctaButton', 'Vedi tutto "A Modo Mio"', 'home', 'Sezione A Modo Mio (home): testo pulsante', 23),
('home.events.eyebrow', 'Eventi', 'home', 'Sezione Eventi (home): eyebrow', 30),
('home.events.title', 'Un servizio per ogni occasione', 'home', 'Sezione Eventi (home): titolo', 31),
('home.events.description', 'Dalla cena intima al matrimonio con cento invitati: definiamo insieme menu, formula di servizio e tempistiche.', 'home', 'Sezione Eventi (home): descrizione', 32),
('home.events.ctaButton', 'Scopri tutti gli eventi', 'home', 'Sezione Eventi (home): testo pulsante', 33),
('home.contact.eyebrow', 'Contatti', 'home', 'Sezione Contatti (home): eyebrow', 40),
('home.contact.title', 'Parliamo del tuo evento', 'home', 'Sezione Contatti (home): titolo', 41),
('home.contact.description', 'Scrivimi su WhatsApp per una risposta rapida, oppure manda una email con i dettagli: data, numero di invitati e cosa hai in mente.', 'home', 'Sezione Contatti (home): descrizione', 42),
('home.contact.whatsappButton', 'Scrivimi su WhatsApp', 'home', 'Sezione Contatti (home): pulsante WhatsApp', 43),
('home.contact.emailButton', 'Invia una email', 'home', 'Sezione Contatti (home): pulsante Email', 44),
('home.contact.pageLinkButton', 'Vai alla pagina contatti completa', 'home', 'Sezione Contatti (home): link pagina completa', 45),
('home.reviews.eyebrowGoogle', 'Recensioni Google', 'home', 'Sezione Recensioni (home): eyebrow con recensioni Google', 50),
('home.reviews.titleGoogle', 'Cosa dicono i miei ospiti su Google', 'home', 'Sezione Recensioni (home): titolo con recensioni Google', 51),
('home.reviews.leaveReviewButton', 'Lascia una recensione', 'home', 'Sezione Recensioni (home): pulsante "lascia una recensione"', 52),
('home.reviews.eyebrowFallback', 'Le voci di chi ha assaggiato', 'home', 'Sezione Recensioni (home): eyebrow senza Google', 53),
('home.reviews.titleFallback', 'Cosa raccontano i miei ospiti', 'home', 'Sezione Recensioni (home): titolo senza Google', 54),
('home.newsletter.title', 'Ricette, eventi e novità via email', 'home', 'Sezione Newsletter (home): titolo', 60),
('home.newsletter.description', 'Una mail ogni tanto, niente spam: nuove ricette di "A Modo Mio", disponibilità per gli eventi e qualche consiglio di cucina napoletana.', 'home', 'Sezione Newsletter (home): descrizione', 61),
('home.newsletter.placeholder', 'La tua email', 'home', 'Sezione Newsletter (home): placeholder campo email', 62),
('home.newsletter.submitButton', 'Iscrivimi', 'home', 'Sezione Newsletter (home): testo pulsante', 63),
('home.newsletter.successMessage', 'Iscrizione completata! Controlla la tua casella email a breve.', 'home', 'Sezione Newsletter (home): messaggio di successo', 64),
('home.newsletter.disclaimer', 'Iscrivendoti accetti di ricevere comunicazioni periodiche. Puoi annullare l''iscrizione in qualsiasi momento.', 'home', 'Sezione Newsletter (home): nota legale', 65),
('common.discoverMore', 'Scopri di più', 'common', 'Etichetta link "Scopri di più" (card servizi/eventi)', 1),
('common.notFound.title', 'Pagina non trovata', 'common', 'Pagina 404: titolo', 10),
('common.notFound.description', 'Questa pagina non esiste, o è stata spostata. Torna alla home per continuare a curiosare.', 'common', 'Pagina 404: descrizione', 11),
('common.notFound.button', 'Torna alla home', 'common', 'Pagina 404: testo pulsante', 12),
('services.page.eyebrow', 'Servizi', 'services', 'Pagina Servizi: eyebrow', 1),
('services.page.title', 'Tre modi per portare la mia cucina da te', 'services', 'Pagina Servizi: titolo', 2),
('services.page.description', 'Dalla cena tra amici al lancio della tua attività: ogni servizio è pensato su misura, partendo da quello che ti serve davvero.', 'services', 'Pagina Servizi: descrizione', 3),
('services.cta.title', 'Non sai quale servizio fa per te?', 'services', 'Pagina Servizi: titolo box finale', 10),
('services.cta.description', 'Scrivimi su WhatsApp raccontandomi cosa hai in mente: ti aiuto a capire la formula più adatta.', 'services', 'Pagina Servizi: descrizione box finale', 11),
('services.cta.button', 'Scrivimi su WhatsApp', 'services', 'Pagina Servizi: pulsante box finale', 12),
('services.detail.backLabel', 'Tutti i servizi', 'services', 'Dettaglio servizio: link indietro', 20),
('services.detail.cta.title', 'Ti interessa questo servizio?', 'services', 'Dettaglio servizio: titolo box finale', 21),
('services.detail.cta.description', 'Scrivimi su WhatsApp raccontandomi cosa hai in mente: ti rispondo con disponibilità e prima proposta.', 'services', 'Dettaglio servizio: descrizione box finale', 22),
('services.detail.cta.button', 'Scrivimi su WhatsApp', 'services', 'Dettaglio servizio: pulsante box finale', 23),
('events.page.eyebrow', 'Eventi', 'events', 'Pagina Eventi: eyebrow', 1),
('events.page.title', 'Un servizio per ogni occasione', 'events', 'Pagina Eventi: titolo', 2),
('events.page.description', 'Dalla cena per due persone al matrimonio con cento invitati: ogni evento ha una formula di servizio dedicata.', 'events', 'Pagina Eventi: descrizione', 3),
('events.menuBanner.label', 'Menu in evidenza per gli eventi', 'events', 'Pagina Eventi: etichetta banner menu attivo', 4),
('events.process.eyebrow', 'Come funziona', 'events', 'Pagina Eventi: eyebrow sezione "come funziona"', 10),
('events.process.title', 'Dal primo messaggio al giorno dell''evento', 'events', 'Pagina Eventi: titolo sezione "come funziona"', 11),
('events.process.step1.title', 'Raccontami l''evento', 'events', 'Pagina Eventi: step 1 titolo', 12),
('events.process.step1.text', 'Data, numero di invitati, location e budget di riferimento.', 'events', 'Pagina Eventi: step 1 testo', 13),
('events.process.step2.title', 'Costruiamo il menu', 'events', 'Pagina Eventi: step 2 titolo', 14),
('events.process.step2.text', 'Proposta su misura, con eventuale degustazione preliminare.', 'events', 'Pagina Eventi: step 2 testo', 15),
('events.process.step3.title', 'Organizziamo il servizio', 'events', 'Pagina Eventi: step 3 titolo', 16),
('events.process.step3.text', 'Definiamo tempistiche, allestimento e personale di sala se necessario.', 'events', 'Pagina Eventi: step 3 testo', 17),
('events.process.step4.title', 'Il giorno dell''evento', 'events', 'Pagina Eventi: step 4 titolo', 18),
('events.process.step4.text', 'Arrivo con tutto il necessario: tu pensi solo a goderti la serata.', 'events', 'Pagina Eventi: step 4 testo', 19),
('events.cta.title', 'Hai già una data in mente?', 'events', 'Pagina Eventi: titolo box finale', 20),
('events.cta.description', 'Scrivimi su WhatsApp con i dettagli del tuo evento: ti rispondo con disponibilità e prima proposta di menu.', 'events', 'Pagina Eventi: descrizione box finale', 21),
('events.cta.button', 'Scrivimi su WhatsApp', 'events', 'Pagina Eventi: pulsante box finale', 22),
('events.detail.backLabel', 'Tutti gli eventi', 'events', 'Landing evento: link indietro', 30),
('events.detail.cta.title', 'Hai già una data in mente?', 'events', 'Landing evento: titolo box finale', 31),
('events.detail.cta.description', 'Scrivimi su WhatsApp con i dettagli del tuo evento: ti rispondo con disponibilità e prima proposta.', 'events', 'Landing evento: descrizione box finale', 32),
('events.detail.cta.button', 'Scrivimi su WhatsApp', 'events', 'Landing evento: pulsante box finale', 33),
('recipes.page.eyebrow', 'A Modo Mio', 'recipes', 'Pagina A Modo Mio: eyebrow', 1),
('recipes.page.title', 'Cosa porto sulla tua tavola', 'recipes', 'Pagina A Modo Mio: titolo', 2),
('recipes.page.description', 'Una selezione di "A Modo Mio" che uso per costruire i menu: ogni servizio viene poi personalizzato in base ai tuoi gusti, alle stagioni e all''occasione.', 'recipes', 'Pagina A Modo Mio: descrizione', 3),
('recipes.menuBanner.label', 'In vetrina ora nel negozio', 'recipes', 'Pagina A Modo Mio: etichetta banner menu attivo', 4),
('recipes.emptyCategory', 'Nessun piatto disponibile in questa categoria al momento.', 'recipes', 'Pagina A Modo Mio: messaggio categoria vuota', 5),
('recipes.category.tutti', 'Tutti i piatti', 'recipes', 'Pagina A Modo Mio: filtro "Tutti"', 10),
('recipes.category.antipasti', 'Antipasti', 'recipes', 'Pagina A Modo Mio: filtro "Antipasti"', 11),
('recipes.category.primi', 'Primi', 'recipes', 'Pagina A Modo Mio: filtro "Primi"', 12),
('recipes.category.secondi', 'Secondi', 'recipes', 'Pagina A Modo Mio: filtro "Secondi"', 13),
('recipes.category.dolci', 'Dolci', 'recipes', 'Pagina A Modo Mio: filtro "Dolci"', 14),
('recipes.cta.title', 'Vuoi un menu pensato per te?', 'recipes', 'Pagina A Modo Mio: titolo box finale', 20),
('recipes.cta.description', 'Raccontami l''occasione, il numero di invitati e le tue preferenze: costruiamo insieme il menu giusto.', 'recipes', 'Pagina A Modo Mio: descrizione box finale', 21),
('recipes.cta.button', 'Parliamone su WhatsApp', 'recipes', 'Pagina A Modo Mio: pulsante box finale', 22),
('contact.page.eyebrow', 'Contatti', 'contact', 'Pagina Contatti: eyebrow', 1),
('contact.page.title', 'Parliamo del tuo progetto', 'contact', 'Pagina Contatti: titolo', 2),
('contact.page.description', 'Scrivimi su WhatsApp per una risposta rapida, oppure compila il form: ti rispondo entro 24 ore.', 'contact', 'Pagina Contatti: descrizione', 3),
('contact.whatsappCard.title', 'WhatsApp aziendale', 'contact', 'Pagina Contatti: titolo box WhatsApp', 10),
('contact.whatsappCard.description', 'Il modo più veloce per ricevere disponibilità e prima proposta di menu.', 'contact', 'Pagina Contatti: descrizione box WhatsApp', 11),
('contact.emailCard.title', 'Email', 'contact', 'Pagina Contatti: titolo box Email', 12),
('contact.emailCard.description', 'Per richieste più strutturate o preventivi per eventi importanti.', 'contact', 'Pagina Contatti: descrizione box Email', 13),
('contact.form.title', 'Oppure scrivimi qui', 'contact', 'Pagina Contatti: titolo form', 20),
('contact.form.successMessage', 'Messaggio inviato! Ti risponderò il prima possibile.', 'contact', 'Pagina Contatti: messaggio di successo', 21),
('contact.form.submitButton', 'Invia messaggio', 'contact', 'Pagina Contatti: pulsante invio', 22),
('about.page.eyebrow', 'La mia storia', 'about', 'Pagina La mia storia: eyebrow', 0),
('about.page.description', 'Non un''azienda, ma un percorso: dalla cucina di famiglia alle cucine professionali di Napoli, fino a diventare il servizio su misura che porto oggi sulla tua tavola.', 'about', 'Pagina La mia storia: descrizione hero', 1),
('about.milestones.heading', 'Le tappe della mia storia', 'about', 'Pagina La mia storia: titolo tappe', 2),
('about.values.heading', 'I principi della mia cucina', 'about', 'Pagina La mia storia: titolo principi', 3),
('footer.tagline', 'Chef a domicilio, eventi privati e consulenza per nuove attività a {city}.', 'footer', 'Footer: frase sotto il nome del brand (usa {city} per la città)', 1),
('footer.sitemapHeading', 'Mappa del sito', 'footer', 'Footer: titolo colonna "mappa del sito"', 2),
('footer.contactHeading', 'Contatti', 'footer', 'Footer: titolo colonna "contatti"', 3);
